<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Apsis.Utilities</PackageId>
    <Description></Description>
    <PackageTags>general;utilities;tools;random;math</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
