<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Apsis.Units</PackageId>
    <Description></Description>
    <PackageTags>si;angle;distance;units;meters;radians;degrees;kilometers</PackageTags>
    <RepositoryUrl></RepositoryUrl>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageReadmeFile></PackageReadmeFile>
    <Authors>Charles Rasberry</Authors>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../../docs/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
</Project>
