<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Apsis.Time</PackageId>
    <Description></Description>
    <PackageTags>time;julian;julian2000;julianday;day;microsecond;year;month;second;J2000;epoch</PackageTags>
    <RepositoryUrl></RepositoryUrl>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageReadmeFile></PackageReadmeFile>
    <Authors>Charles Rasberry</Authors>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../../docs/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
</Project>
