<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Apsis.Mechanics</PackageId>
    <Description></Description>
    <PackageTags>wgs84;azimuth;elevation;satellite;orbital;topocentric;leo;electromagnetic;waves</PackageTags>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../../docs/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
